# Generated by Django 4.2.7 on 2023-11-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter user identifier', max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.CharField(help_text='Enter a brief comment for the video', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the profile', max_length=30)),
                ('genre', models.CharField(help_text='Enter a genre identifier', max_length=30)),
                ('priority', models.IntegerField(help_text='Enter a priority')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.IntegerField()),
                ('title', models.CharField(help_text='Enter the video title', max_length=128)),
                ('description', models.CharField(help_text='Enter a brief description of the video', max_length=8000)),
                ('channel', models.CharField(help_text='Enter a channel identifier', max_length=64)),
                ('genre', models.CharField(help_text='Enter a genre identifier', max_length=30)),
            ],
        ),
    ]
