# Generated by Django 4.2.7 on 2023-11-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytrecplus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
