# Generated by Django 4.2.7 on 2023-11-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytrecplus', '0002_comment_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
